name: 'Action JS Template'
description: 'A javascript Action template with environment variable support and configurable greetings.'
author: '@renan-alm'

branding:
  # https://actions-cool.github.io/github-action-branding/
  icon: 'file'
  color: 'blue'

inputs:
  user-name:
    description: 'Name to greet (used when use-env-vars is false)'
    required: false
    default: 'Renan'
  use-env-vars:
    description: 'Whether to use environment variables instead of inputs'
    required: false
    default: 'false'

outputs:
  greeting:
    description: 'The greeting message'
  time:
    description: 'The time the action ran'

runs:
  using: 'node20'
  main: 'dist/index.js'
